### ISSUE TITLE
Polytone Missing element ResourceKey[minecraft:worldgen/biome / alexscaves:magnetic_caves]

### ISSUE THREAD

**Issue by BitzThe8Bit** [MehVahdJukaar/polytone#129]
Full log here.
[polytone.log](https://github.com/user-attachments/files/18187318/polytone.log)

This happens when I attempt to use the Fogulous resource pack, upon starting a world or loading the resource pack during it, it will disable the resource pack and give me the log above. I've tested other packs that alter the biome fog. Same story.
The mods I'm using are purely worldgen mods on 1.21.4. No extra blocks or items. I am also using entity model/texture features, and obviously, the newest version of Polytone. I do not have Alexs' Caves installed currently, but I used it in the past with an older version of Polytone. How do I fix this?

**Comment by MehVahdJukaar** [comment]
Seems like the pack is invalid as it is referencing an entry from another mod without neither a load condition on the JSON, a polytone condition or an optional entry in the target.
Either install that mod that it's using, report to the pack author or edit the file yourself removing or making that reference optional.
Note that in previous versions this thing might have not occurred since due to a bug poltrone would not throw an error here like it was meant to

**Comment by BitzThe8Bit** [comment]
Yeah, I checked the pack, it's calling for Candy Cavities and Primordial Caves, but not Magnetic Caves. I tested another fog resource pack that only touches vanilla Minecraft. It still shoots me this same log.

**Comment by MehVahdJukaar** [comment]
send the log from the second one. It cant shoot the same one as the one you sent is complaining about missing biomes that are not there as alex caves isnt even for 1.21

**Comment by BitzThe8Bit** [comment]
[polytone.log](https://github.com/user-attachments/files/18203642/polytone.log)
Here. It looked the same to me, I tested this right now.

**Comment by MehVahdJukaar** [comment]
well you say it just touches vanilla minecraft but no it doesnt. its referencing those biomes and they dont exist so polytone complains about them. report to pack author they should be made optional entries or optional values
