### ISSUE TITLE
Issue of changing Redstone dust particle

### ISSUE THREAD

**Issue by MrdotDex** [MehVahdJukaar/polytone#47]
I've been able to change the color of the redstone wire AND it changes the redstone dust color to match, but the redstone dust color coming off of the repeaters, torches ect... doesn't change to the color of the redstone color.

I'm trying to change the color of redstone to blue and the particles as well, but as stated above, only the dust for the redstone wire gets changed appropriately, the rest stay the vanilla color of red.

I tried particle modifiers but they change the minecraft:dust particle for other blocks as well AND I'd like to keep things as close to vanilla as possible, meaning, if you change the color of the minecraft:dust particle inside of a particle modifier, I don't know if it's possible to make it cycle through the different color brightness's of redstone.

Also particle modifiers's "target" attribute doesn't seem to work, at least for repeaters.

Here's my particle modifier file text:
```json
{
  "targets": ["minecraft:dust"],
  "red": "0.027",
  "green": "0.404",
  "blue": "0.902",
  "filter": {
    "block": "minecraft:repeater"
  }
}
```

**Comment by MehVahdJukaar** [comment]
so i see the wiki actually has some incorrect info. 
When a particle it spawned it reatains no history of where of why it was spawned. The filter block is only able to do so because some of them do have a BlockState field, which is used to determine their texture. These are just terrain particles or item broken particles. Unlike whats written on the wiki, dust particles are not included. I'll update that.

your json seems correct except for the filter block which wl be ignored.
Since dust particles are used in many places not just redstone, the easiest way to change redstone dust color is via the color.properties /color.json file. That allows to replace the color array that is used across all those things. Check that section

**Comment by MehVahdJukaar** [comment]
try new version. 1.20.1 for now

**Comment by MrdotDex** [comment]
I can confirm that the redstone colors in the colors.json are now appearing in the dust in redstone torches, repeater ect...
