### ISSUE TITLE
mark 2.3.10 version as a beta

### ISSUE THREAD

**Issue by girshcatt** [MehVahdJukaar/polytone#79]
mark 2.3.10 version as a beta, because you did this change: removed some hack to get biome watercolor working on sodium since its new version has fixed the bug that made it required

so you broke this thing for sodium 0.5.11, which is the last release
sodium 0.6.0 is in beta, so mark polytone versions for new sodium as a beta

**Comment by MehVahdJukaar** [comment]
Beta versions dont work like a copyleft license. You could have a perfectly working version of a library and a beta version of s mod that uses it because that particular mod just isn't finished yet. Polytone is. If you use it with old sodium you'll simply get no watercolor for a sodium bug, not a polytone one. Code I removed was a Jacky workaround that I would have removed anyways and simply makes it work just for flat colours in some particular instances
